/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        surface: "#f8f9ff",
        "surface-dim": "#cbdbf5",
        "surface-bright": "#f8f9ff",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#eff4ff",
        "surface-container": "#e5eeff",
        "surface-container-high": "#dce9ff",
        "surface-container-highest": "#d3e4fe",
        "on-surface": "#0b1c30",
        "on-surface-variant": "#40474f",
        "inverse-surface": "#213145",
        "inverse-on-surface": "#eaf1ff",
        outline: "#707881",
        "outline-variant": "#c0c7d1",
        "surface-tint": "#006399",
        primary: "#00507d",
        "on-primary": "#ffffff",
        "primary-container": "#0369a1",
        "on-primary-container": "#cbe4ff",
        "inverse-primary": "#94ccff",
        secondary: "#00668a",
        "on-secondary": "#ffffff",
        "secondary-container": "#40c2fd",
        "on-secondary-container": "#004d6a",
        tertiary: "#444c62",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#5c647a",
        "on-tertiary-container": "#dae1fc",
        error: "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        "primary-fixed": "#cde5ff",
        "primary-fixed-dim": "#94ccff",
        "on-primary-fixed": "#001d32",
        "on-primary-fixed-variant": "#004b74",
        "secondary-fixed": "#c4e7ff",
        "secondary-fixed-dim": "#7bd0ff",
        "on-secondary-fixed": "#001e2c",
        "on-secondary-fixed-variant": "#004c69",
        "tertiary-fixed": "#dae2fd",
        "tertiary-fixed-dim": "#bec6e0",
        "on-tertiary-fixed": "#131b2e",
        "on-tertiary-fixed-variant": "#3f465c",
        background: "#f8f9ff",
        "on-background": "#0b1c30",
        "surface-variant": "#d3e4fe",
        // Academic semantics
        "academic-mastered": "#059669",
        "academic-mastered-bg": "#ecfdf5",
        "academic-progress": "#d97706",
        "academic-progress-bg": "#fffbeb",
        "academic-revision": "#e11d48",
        "academic-revision-bg": "#fff1f2",
      },
      fontFamily: {
        serif: ["Newsreader", "Georgia", "serif"],
        sans: ["Manrope", "system-ui", "-apple-system", "sans-serif"],
        headline: ["Newsreader", "serif"],
        body: ["Manrope", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "0.5rem",
        sm: "0.25rem",
        md: "0.75rem",
        lg: "1rem",
        xl: "1.5rem",
        full: "9999px",
      },
      boxShadow: {
        subtle: "0 1px 3px 0 rgba(11, 28, 48, 0.04), 0 1px 2px -1px rgba(11, 28, 48, 0.04)",
        card: "0 4px 20px -2px rgba(15, 23, 42, 0.05), 0 1px 3px 0 rgba(15, 23, 42, 0.02)",
        elevated: "0 12px 32px -4px rgba(3, 105, 161, 0.08), 0 4px 12px -2px rgba(15, 23, 42, 0.04)",
      },
      spacing: {
        gutter: "1.5rem",
        "gutter-desktop": "2.5rem",
        margin: "1.25rem",
        "margin-desktop": "4rem",
        "space-xs": "0.25rem",
        "space-sm": "0.5rem",
        "space-md": "1rem",
        "space-lg": "1.5rem",
        "space-xl": "2.5rem",
        "space-2xl": "4rem",
      },
    },
  },
  plugins: [],
};
