/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        // Education Platform Core Brand Palette (DESIGN.md)
        brand: {
          blue: "#00A8F0",
          yellow: "#F6C20F",
          purple: "#6C63D9",
          green: "#35C978",
          navy: "#12365A",
          bg: "#F5F8FC",
          card: "#FFFFFF",
          border: "#E2E8F0",
          text: "#12365A",
          secondary: "#64748B",
          muted: "#94A3B8",
          error: "#DC3545",
        },
        // Semantic Mappings & Component Compatibility
        primary: {
          DEFAULT: "#00A8F0",
          hover: "#0092D1",
          dark: "#12365A",
          light: "#E0F4FD",
        },
        "primary-container": "#12365A",
        "on-primary": "#ffffff",
        "on-primary-container": "#cbe4ff",
        secondary: {
          DEFAULT: "#6C63D9",
          light: "#F0EFFF",
        },
        surface: "#FFFFFF",
        "surface-dim": "#F1F5F9",
        "surface-bright": "#FFFFFF",
        "surface-container-lowest": "#FFFFFF",
        "surface-container-low": "#F5F8FC",
        "surface-container": "#EEF4FA",
        "surface-container-high": "#E2E8F0",
        "surface-container-highest": "#CBD5E1",
        "on-surface": "#12365A",
        "on-surface-variant": "#64748B",
        "inverse-surface": "#12365A",
        "inverse-on-surface": "#F5F8FC",
        outline: "#E2E8F0",
        "outline-variant": "#CBD5E1",
        "surface-tint": "#00A8F0",
        background: "#F5F8FC",
        "on-background": "#12365A",
        "surface-variant": "#E0F2FE",
        error: "#DC3545",
        "on-error": "#ffffff",
        "error-container": "#FEE2E2",
        "on-error-container": "#991B1B",
        // Academic Semantics (DESIGN.md Section 5 & 23)
        "academic-learning": "#00A8F0",
        "academic-practice": "#6C63D9",
        "academic-mastered": "#35C978",
        "academic-mastered-bg": "#ECFDF5",
        "academic-progress": "#00A8F0",
        "academic-progress-bg": "#E0F2FE",
        "academic-revision": "#F6C20F",
        "academic-revision-bg": "#FEFCE8",
        "academic-due": "#F6C20F",
        "academic-error": "#DC3545",
      },
      fontFamily: {
        serif: ["'Inria Serif'", "Georgia", "serif"],
        sans: ["'Roboto'", "system-ui", "-apple-system", "sans-serif"],
        headline: ["'Inria Serif'", "Georgia", "serif"],
        body: ["'Roboto'", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "8px",
        sm: "4px",
        md: "8px",
        card: "12px",
        lg: "12px",
        modal: "16px",
        xl: "16px",
        "2xl": "20px",
        full: "9999px",
      },
      boxShadow: {
        subtle: "0 1px 3px 0 rgba(18, 54, 90, 0.05), 0 1px 2px -1px rgba(18, 54, 90, 0.04)",
        card: "0 2px 8px -1px rgba(18, 54, 90, 0.06), 0 1px 4px -1px rgba(18, 54, 90, 0.04)",
        elevated: "0 10px 25px -4px rgba(18, 54, 90, 0.08), 0 4px 10px -2px rgba(18, 54, 90, 0.04)",
        modal: "0 20px 35px -6px rgba(18, 54, 90, 0.16), 0 8px 16px -4px rgba(18, 54, 90, 0.08)",
      },
      spacing: {
        gutter: "1.5rem",
        "gutter-desktop": "2.5rem",
        margin: "1.25rem",
        "margin-desktop": "4rem",
        "space-xs": "0.25rem",
        "space-sm": "0.5rem",
        "space-md": "1rem",
        "space-lg": "1.5rem",
        "space-xl": "2.5rem",
        "space-2xl": "4rem",
      },
    },
  },
  plugins: [],
};
